fmt.filex <- function(){
    fmt = list(
        `%2i`=c('CU','FL','SA','IC','MP','MI','MF','MR','MC',
                        'MT','ME','MH','SM','A','C','F','H','L',
                        'N','O','P','R','T'),
        `%2s`=c('CR'),
        ` %4s`=c('SLTX'),
        ` %-6s`=c('ECO2','EDAY','EDEW','EMAX','EMIN','ERAD','ERAIN','EWIND'),
        `%6.0f`=c('PLDR','FAMC','FAMK','FAMN','FAMO','FAMP','FLOB','FLSA',
            'FLST','FDEP','FLDD','FLDS','IAMT','ICBL','ICND','ICRT','IDEP',
            'IEPT','ITHR','ITHRL','ITHRU','PAGE','PLRD','PLRS','PLSP','PLWT',
            'RAMT','RDEP','RINP','SABL','SLDP','TDEP','ICRES','ICRIP','ICRID'),
        `%6.1f`=c('HAREA','HLEN','HPC','IRVAL','PENV','PLDP','PLEN','PLPH',
            'PPOP','PPOE','SAHB','SAHW','SNH4','SNO3','SLEN','FLWR','SLAS',
            '.SLEN','.FLWR','.SLAS','ICWD'),
        `%6.2f`=c('ICRE','IEFF','RESK','RESN','RESP','SADM','SAKE','SAPX',
            'SAPW','ICRN','ICREN','ICREP','IREFF'),
        `%6.3f`=c('SAOC','SANI','SAPHW','SH2O'),
        `%6i`=c('PRNO','PLEN','HRNO'),
        `%6s`=c('FACD','FLDT','FMCD','FOCD','HCOM','HSIZE','HSTG','IAME',
            'IOFF','IROP','PCR','PLAY','PLDS','PLME','RCOD','SMHB','SMKE',
            'SMPX','TIMPL'),
        ` %6s`=c('INGENO'),
        `%6yrdoy`=c('EDATE','PDATE','ODATE','FDATE','HDATE','ICDAT','IDATE',
            'RDATE','SADAT','TDATE'),
        `%7.1f`=c('PAREA'),
        ` %8s`=c('ID_FIELD','WSTA....','WSTA'),
        `  %10s`=c('ID_SOIL'),
        `%11s`=c('GENERAL','OPTIONS','METHODS','MANAGEMENT','OUTPUTS',
            'PLANTING','IRRIGATION','NITROGEN','RESIDUES','HARVEST'),
        ` %9.2f`=c('.....ELEV'),
        ` %15.5f`=c('...........XCRD','...........YCRD'),
        ` %17.1f`=c('.............AREA'),
        `%120s`=c('PEOPLE','ADDRESS','SITE','HARM','CNAME','FLNAME','SANAME',
            'ICNAME','PLNAME','IRNAME','FERNAME','TNAME','HNAME','HARM',
            'CHNOTES','CNOTES','ENVNAME','NOTES')
        )
    return(fmt)
}
