fortran2sprintf<-function(forfmt){
    spr.fmt=vector(length=length(forfmt),mode='character')
    real=grepl('F',forfmt)
    integer=grepl('I',forfmt)
    scientific=grepl('ES',forfmt)
    character=grepl('A',forfmt)
    forfmt=gsub('\\(','',forfmt)
    forfmt=gsub('\\)','',forfmt)
    forfmt=gsub('F','',forfmt)
    forfmt=gsub('I','',forfmt)
    forfmt=gsub('ES','',forfmt)
    forfmt=gsub('A','',forfmt)
    spr.fmt[real]=paste('%',forfmt[real],'f',sep='')
    spr.fmt[integer]=paste('%',forfmt[integer],'d',sep='')
    spr.fmt[scientific]=paste('%',forfmt[scientific],'e',sep='')
    spr.fmt[character]=paste('%',forfmt[character],'s',sep='')
    spr.fmt=gsub(',1Xd','d ',gsub(',2Xd','d  ',spr.fmt))
    spr.fmt=gsub(',1Xe','e ',gsub(',2Xe','e  ',spr.fmt))
    spr.fmt=gsub(',1Xf','f ',gsub(',2Xf','f  ',spr.fmt))
    spr.fmt=gsub(',1Xs','s ',gsub(',2Xs','s  ',spr.fmt))
    spr.fmt=gsub('%1X,',' %',gsub('%2X,','  %',spr.fmt))
    spr.fmt[character]=gsub('%','%-',spr.fmt[character])
    return(spr.fmt)
}

