new.filex <- function(){
return(
    structure(list(EXP.DETAILS = "*EXP.DETAILS:", GENERAL = list(
    "*GENERAL", structure(list(ADDRESS = NA), .Names = "ADDRESS", row.names = c(NA, 
    -1L), class = "data.frame"), structure(list(SITE = NA), .Names = "SITE", row.names = c(NA, 
    -1L), class = "data.frame"), structure(list(NOTES = NA_real_), .Names = "NOTES", row.names = c(NA, 
    -1L), class = "data.frame")), TREATMENTS = list("*TREATMENTS                        -------------FACTOR LEVELS------------", 
    structure(list(N = 1, R = 1, O = 0, C = 0, TNAME = NA, CU = 1, 
        FL = 1, SA = 0, IC = 0, MP = 1, MI = 0, MF = 0, MR = 0, 
        MC = 0, MT = 0, ME = 0, MH = 0, SM = 1), .Names = c("N", 
    "R", "O", "C", "TNAME", "CU", "FL", "SA", "IC", "MP", "MI", 
    "MF", "MR", "MC", "MT", "ME", "MH", "SM"), row.names = 1L, class = "data.frame")), 
    CULTIVARS = list("*CULTIVARS", structure(list(C = 1, CR = NA_character_, 
        INGENO = NA_character_, CNAME = NA_character_), .Names = c("C", 
    "CR", "INGENO", "CNAME"), row.names = 1L, class = "data.frame")), 
    FIELDS = list("*FIELDS", structure(list(L = 1, ID_FIELD = NA, 
        WSTA = NA, FLSA = NA_real_, FLOB = 0, FLDT = " DR000", 
        FLDD = 0, FLDS = 0, FLST = 0, SLTX = NA_real_, SLDP = NA, 
        ID_SOIL = NA, FLNAME = NA_real_), .Names = c("L", "ID_FIELD", 
    "WSTA", "FLSA", "FLOB", "FLDT", "FLDD", "FLDS", "FLST", "SLTX", 
    "SLDP", "ID_SOIL", "FLNAME"), row.names = c(NA, -1L), class = "data.frame"), 
        structure(list(L = 1, XCRD = 0, YCRD = 0, ELEV = 38, 
            AREA = 0, SLEN = 0, FLWR = 0, SLAS = 0), .Names = c("L", 
        "XCRD", "YCRD", "ELEV", "AREA", "SLEN", "FLWR", "SLAS"
        ), row.names = c(NA, -1L), class = "data.frame")), `INITIAL CONDITIONS` = list(
        "*INITIAL CONDITIONS", structure(list(C = 1, PCR = "    WH", 
            ICDAT = NA_integer_, ICRT = NA_real_, ICND = NA_real_, 
            ICRN = NA_real_, ICRE = NA_real_, ICWD = NA_real_, 
            ICRES = NA_real_, ICREN = NA_real_, ICREP = NA_real_, 
            ICRIP = NA_real_, ICRID = NA_real_, ICNAME = NA_real_), .Names = c("C", 
        "PCR", "ICDAT", "ICRT", "ICND", "ICRN", "ICRE", "ICWD", 
        "ICRES", "ICREN", "ICREP", "ICRIP", "ICRID", "ICNAME"
        ), row.names = c(NA, -1L), class = "data.frame"), structure(list(
            C = c(1, 1, 1, 1, 1, 1, 1), ICBL = c(15, 30, 60, 
            90, 120, 150, 180), SH2O = c(NA_real_, NA_real_, 
            NA_real_, NA_real_, NA_real_, NA_real_, NA_real_), 
            SNH4 = c(NA_real_, NA_real_, NA_real_, NA_real_, 
            NA_real_, NA_real_, NA_real_), SNO3 = c(NA_real_, 
            NA_real_, NA_real_, NA_real_, NA_real_, NA_real_, 
            NA_real_)), .Names = c("C", "ICBL", "SH2O", "SNH4", 
        "SNO3"), row.names = c(NA, -7L), class = "data.frame")), 
    `PLANTING DETAILS` = list("*PLANTING DETAILS", structure(list(
        P = 1, PDATE = NA, EDATE = NA, PPOP = NA, PPOE = NA, 
        PLME = "     S", PLDS = "     R", PLRS = 40, PLRD = 0, 
        PLDP = 5.5, PLWT = NA_real_, PAGE = NA_real_, PENV = NA_real_, 
        PLPH = NA_real_, SPRL = 0, PLNAME = NA_real_), .Names = c("P", 
    "PDATE", "EDATE", "PPOP", "PPOE", "PLME", "PLDS", "PLRS", 
    "PLRD", "PLDP", "PLWT", "PAGE", "PENV", "PLPH", "SPRL", "PLNAME"
    ), row.names = c(NA, -1L), class = "data.frame")), `IRRIGATION AND WATER MANAGEMENT` = list(
        "*IRRIGATION AND WATER MANAGEMENT", structure(list(I = 1, 
            EFIR = 1, IDEP = NA_real_, ITHR = NA_real_, IEPT = NA_real_, 
            IOFF = NA_real_, IAME = NA_real_, IAMT = NA_real_, 
            IRNAME = NA_real_), .Names = c("I", "EFIR", "IDEP", 
        "ITHR", "IEPT", "IOFF", "IAME", "IAMT", "IRNAME"), row.names = c(NA, 
        -1L), class = "data.frame"), structure(list(I = c(1, 
        1, 1, 1, 1, 1), IDATE = c(NA, 12011, 12032, 12056, 12074, 
        12093), IROP = c(NA, " IR001", " IR001", " IR001", " IR001", 
        " IR001"), IRVAL = c(NA, 120, 120, 120, 120, 120)), .Names = c("I", 
        "IDATE", "IROP", "IRVAL"), row.names = c(NA, -6L), class = "data.frame")), 
    FERTILIZERS = list("*FERTILIZERS (INORGANIC)", structure(list(
        F = 1, FDATE = NA_integer_, FMCD = " FE004", FACD = " AP002", 
        FDEP = NA_real_, FAMN = NA_real_, FAMP = 0, FAMK = 0, 
        FAMC = 0, FAMO = 0, FOCD = NA_real_, FERNAME = NA_real_), .Names = c("F", 
    "FDATE", "FMCD", "FACD", "FDEP", "FAMN", "FAMP", "FAMK", 
    "FAMC", "FAMO", "FOCD", "FERNAME"), row.names = 1L, class = "data.frame")), 
    `SIMULATION CONTROLS` = list(list("*SIMULATION CONTROLS", 
        structure(list(N = 1, GENERAL = " GE         ", NYERS = 1, 
            NREPS = 1, START = "     S", SDATE = NA, RSEED = 2150, 
            SNAME = NA_real_), .Names = c("N", "GENERAL", "NYERS", 
        "NREPS", "START", "SDATE", "RSEED", "SNAME"), row.names = c(NA, 
        -1L), class = "data.frame"), structure(list(N = 1, OPTIONS = " OP          ", 
            WATER = "    N ", NITRO = "    N ", SYMBI = "    N ", 
            PHOSP = "    N ", POTAS = "    N ", DISES = "    N ", 
            CHEM = "    N ", TILL = "    N"), .Names = c("N", 
        "OPTIONS", "WATER", "NITRO", "SYMBI", "PHOSP", "POTAS", 
        "DISES", "CHEM", "TILL"), row.names = c(NA, -1L), class = "data.frame"), 
        structure(list(N = 1, METHODS = " ME          ", WTHER = "    M ", 
            INCON = "    M ", LIGHT = "    E ", EVAPO = "    R ", 
            INFIL = "    S ", PHOTO = "    R ", HYDRO = "    R ", 
            NSWIT = 1, MESOM = "    G"), .Names = c("N", "METHODS", 
        "WTHER", "INCON", "LIGHT", "EVAPO", "INFIL", "PHOTO", 
        "HYDRO", "NSWIT", "MESOM"), row.names = c(NA, -1L), class = "data.frame"), 
        structure(list(N = 1, MANAGEMENT = " MA          ", PLANT = "    R ", 
            IRRIG = "    R ", FERTI = "    R ", RESID = "    N ", 
            HARVS = "    M"), .Names = c("N", "MANAGEMENT", "PLANT", 
        "IRRIG", "FERTI", "RESID", "HARVS"), row.names = c(NA, 
        -1L), class = "data.frame"), structure(list(N = 1, OUTPUTS = " OU          ", 
            FNAME = "    N ", OVVEW = "    Y ", SUMRY = "    Y ", 
            FROPT = 1, GROUT = "    Y ", CAOUT = "    N ", WAOUT = "    Y ", 
            NIOUT = "    Y ", MIOUT = "    N ", DIOUT = "    N ", 
            LONG = "    Y ", CHOUT = "    N ", OPOUT = "    N"), .Names = c("N", 
        "OUTPUTS", "FNAME", "OVVEW", "SUMRY", "FROPT", "GROUT", 
        "CAOUT", "WAOUT", "NIOUT", "MIOUT", "DIOUT", "LONG", 
        "CHOUT", "OPOUT"), row.names = c(NA, -1L), class = "data.frame"), 
        "@  AUTOMATIC MANAGEMENT", structure(list(N = 1, PLANTING = " PL          ", 
            PFRST = NA_integer_, PLAST = NA_integer_, PH2OL = 40, 
            PH2OU = 100, PH2OD = 30, PSTMX = 40, PSTMN = 10), .Names = c("N", 
        "PLANTING", "PFRST", "PLAST", "PH2OL", "PH2OU", "PH2OD", 
        "PSTMX", "PSTMN"), row.names = c(NA, -1L), class = "data.frame"), 
        structure(list(N = 1, IRRIGATION = " IR          ", IMDEP = 30, 
            ITHRL = 50, ITHRU = 100, IROFF = "GS000 ", IMETH = "IR001 ", 
            IRAMT = 10, IREFF = 1), .Names = c("N", "IRRIGATION", 
        "IMDEP", "ITHRL", "ITHRU", "IROFF", "IMETH", "IRAMT", 
        "IREFF"), row.names = c(NA, -1L), class = "data.frame"), 
        structure(list(N = 1, NITROGEN = " NI          ", NMDEP = 30, 
            NMTHR = 50, NAMNT = 25, NCODE = "FE001 ", NAOFF = "GS000"), .Names = c("N", 
        "NITROGEN", "NMDEP", "NMTHR", "NAMNT", "NCODE", "NAOFF"
        ), row.names = c(NA, -1L), class = "data.frame"), structure(list(
            N = 1, RESIDUES = " RE          ", RIPCN = 100, RTIME = 1, 
            RIDEP = 20), .Names = c("N", "RESIDUES", "RIPCN", 
        "RTIME", "RIDEP"), row.names = c(NA, -1L), class = "data.frame"), 
        structure(list(N = 1, HARVEST = " HA          ", HFRST = 0L, 
            HLAST = 82289L, HPCNP = 100, HPCNR = 0), .Names = c("N", 
        "HARVEST", "HFRST", "HLAST", "HPCNP", "HPCNR"), row.names = c(NA, 
        -1L), class = "data.frame")))), .Names = c("EXP.DETAILS", 
"GENERAL", "TREATMENTS", "CULTIVARS", "FIELDS", "INITIAL CONDITIONS", 
"PLANTING DETAILS", "IRRIGATION AND WATER MANAGEMENT", "FERTILIZERS", 
"SIMULATION CONTROLS"))
)
}

