# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lmatch <- function(soil_data, depths_in, depths_out) {
    .Call(`_dssatR_lmatch`, soil_data, depths_in, depths_out)
}

read_forage_spe <- function(file_name) {
    .Call(`_dssatR_read_forage_spe`, file_name)
}

